#!/usr/bin/env bash
#
# supplementary_analyses.sh
# -------------------------
# Supplementary probe analyses, for the Ubuntu server.
#
# Additions to the published MLP results, not replacements: nothing here writes
# to by_layer_mlp.csv, cv_preds/, or any other main-pipeline output. Everything
# lands in Data/supplementary/<slug>/.
#
#   1. re-extract embeddings   (the main pipeline deletes them)
#   2. linear probe            same folds as the MLP, so directly comparable
#   3. PLS component sweep     how many dimensions carry the ordering signal
#   4. steering                causal test: is the direction USED, not just decodable
#   5. delete embeddings       (optional; they are very large)
#
# COVERAGE
#   The job list is generated by supplementary_jobs.py, which reads it off
#   Results/*/by_layer_mlp.csv — i.e. exactly the cells the paper reports, at
#   exactly the layer depths they were run at. Nothing is re-derived, so BabyLM
#   and Pythia get their full by-layer and by-checkpoint coverage while
#   GPT-2 / OLMo / Llama get final-layer only, matching the pipeline.
#
#   Preview the job list without running anything:
#       python Scripts/supplementary_jobs.py | column -t
#
# RESTARTING
#   Each cell writes Data/supplementary/<slug>/.done once every step has
#   finished. Re-running the script skips those cells, so a crashed run is
#   resumed by issuing the same command again rather than starting over. A cell
#   that fails is logged and the run continues; failures are listed at the end.
#   FORCE=1 ignores the markers and redoes everything.
#
# Usage:
#   bash Scripts/supplementary_analyses.sh
#   ONLY="babylm pythia"        bash Scripts/supplementary_analyses.sh
#   FINAL_ONLY=1                bash Scripts/supplementary_analyses.sh
#   EXCLUDE="allenai_OLMo-2-1124-1B" bash Scripts/supplementary_analyses.sh
#   KEEP_EMBEDDINGS=1 SKIP_STEERING=1 bash Scripts/supplementary_analyses.sh
#   FORCE=1                     bash Scripts/supplementary_analyses.sh
#
set -euo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-python}"
GPU="${GPU:-0}"
PLS_KMAX="${PLS_KMAX:-15}"
KEEP_EMBEDDINGS="${KEEP_EMBEDDINGS:-0}"
SKIP_STEERING="${SKIP_STEERING:-0}"
N_STEER_PAIRS="${N_STEER_PAIRS:-500}"
STEER_ALPHAS="${STEER_ALPHAS:--4 -2 -1 0 1 2 4}"
DRY_RUN="${DRY_RUN:-0}"

OUT_ROOT="$BASE/Data/supplementary"
LOG_DIR="$OUT_ROOT/logs"
mkdir -p "$LOG_DIR"

log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }

# ── build the job list from what the paper actually reports ──────────────────
JOB_ARGS=()
[[ -n "${ONLY:-}" ]]       && JOB_ARGS+=(--only $ONLY)
[[ "${FINAL_ONLY:-0}" == "1" ]] && JOB_ARGS+=(--final-only)
[[ -n "${EXCLUDE:-}" ]]    && JOB_ARGS+=(--exclude $EXCLUDE)

JOBS="$(mktemp)"
trap 'rm -f "$JOBS"' EXIT
"$PYTHON" "$BASE/Scripts/supplementary_jobs.py" "${JOB_ARGS[@]}" > "$JOBS"
N_JOBS=$(wc -l < "$JOBS")
log "job list: $N_JOBS cells"

if [[ "$DRY_RUN" == "1" ]]; then
  printf 'slug\thf_id\trevision\tn_layers\tbatch\tlayers\n'
  cat "$JOBS"
  exit 0
fi

IDX=0
FAILED=()
while IFS=$'\t' read -r SLUG HF_ID REVISION NLAYERS BATCH LAYERS; do
  IDX=$((IDX + 1))
  LOG="$LOG_DIR/${SLUG}.log"
  N_L=$(wc -w <<< "$LAYERS")
  # Two markers, because a cell run with SKIP_STEERING=1 is not as complete as
  # one run without it. Otherwise a later steering run would silently skip every
  # cell finished by an earlier no-steering run.
  DONE_FULL="$OUT_ROOT/$SLUG/.done"
  DONE_NOSTEER="$OUT_ROOT/$SLUG/.done_nosteer"
  if [[ "$SKIP_STEERING" == "1" ]]; then
    DONE_MARK="$DONE_NOSTEER"
  else
    DONE_MARK="$DONE_FULL"
  fi

  # Resume: a cell that finished every step wrote its marker. Re-running the
  # script after a crash therefore picks up where it stopped instead of starting
  # over. FORCE=1 re-runs everything regardless.
  if [[ "${FORCE:-0}" != "1" ]] && { [[ -f "$DONE_FULL" ]] ||
       { [[ "$SKIP_STEERING" == "1" ]] && [[ -f "$DONE_NOSTEER" ]]; }; }; then
    log "=== [$IDX/$N_JOBS] $SLUG  already complete, skipping (FORCE=1 to redo)"
    continue
  fi

  log "=== [$IDX/$N_JOBS] $SLUG  rev=$REVISION  layers=$N_L  -> $LOG"

  REV_ARGS=()
  [[ "$REVISION" != "-" ]] && REV_ARGS=(--revision "$REVISION")

  # Per-cell failure must not abort the remaining cells; collect and report.
  CELL_OK=1
  {
    log "--- 1. extracting embeddings: layers [$LAYERS] ---"
    for COND in "default:binomial:novel_embeddings" \
                "attn_zeroed:attn_zeroed:novel_embeddings_attn_zeroed"; do
      IFS=':' read -r CNAME CCTX CDIR <<< "$COND"
      TARGET="$BASE/Data/$CDIR/$SLUG"
      # Every requested layer must be present. Checking for "any layer_*.npz"
      # would treat a cell interrupted mid-extraction as complete and leave
      # layers silently missing.
      MISSING=""
      for L in $LAYERS; do
        [[ -s "$TARGET/layer_${L}.npz" ]] || MISSING="$MISSING $L"
      done
      if [[ -z "$MISSING" ]]; then
        log "  $CNAME: all $N_L layers present, skipping extraction"
        continue
      fi
      if compgen -G "$TARGET/layer_*.npz" > /dev/null 2>&1; then
        log "  $CNAME: partial extraction, missing layers [$MISSING ]; re-extracting all"
      else
        log "  $CNAME: extracting novel-set embeddings"
      fi
      "$PYTHON" "$BASE/Scripts/extract_embeddings.py" \
        --model "$HF_ID" "${REV_ARGS[@]}" \
        --data novel --context "$CCTX" \
        --extract word --pool mean \
        --layer $LAYERS \
        --batch-size "$BATCH" --gpu "$GPU" --out "$TARGET"
    done

    log "--- 2+3. linear probe and PLS component sweep ---"
    "$PYTHON" "$BASE/Scripts/supplementary_probes.py" \
      --model-slug "$SLUG" --num-layers "$NLAYERS" \
      --conditions default attn_zeroed \
      --modes mean_pooled words_only \
      --splits pair_novel word_novel \
      --pls-kmax "$PLS_KMAX" --save-directions \
      --layers $LAYERS \
      --out-dir "$OUT_ROOT/$SLUG" --gpu "$GPU"

    # Steering only where several layers were extracted. Applying the
    # intervention at the final layer alone edits the answer immediately before
    # readout and demonstrates nothing; early-layer efficacy is the whole point.
    if [[ "$SKIP_STEERING" != "1" ]] && [[ "$N_L" -ge 3 ]]; then
      log "--- 4. steering: apply layers=[$LAYERS] alphas=[$STEER_ALPHAS] ---"
      "$PYTHON" "$BASE/Scripts/steering.py" \
        --model "$HF_ID" "${REV_ARGS[@]}" --slug "$SLUG" \
        --fit-layer "$NLAYERS" --fit-per-layer \
        --layers $LAYERS --alphas $STEER_ALPHAS \
        --n-pairs "$N_STEER_PAIRS" --data novel --gpu "$GPU" \
        --out "$OUT_ROOT/$SLUG/steering.csv"
    elif [[ "$SKIP_STEERING" != "1" ]]; then
      log "--- 4. steering SKIPPED: only $N_L layer(s) available for this cell ---"
    fi

    if [[ "$KEEP_EMBEDDINGS" != "1" ]]; then
      log "--- 5. removing embeddings (KEEP_EMBEDDINGS=1 to retain) ---"
      rm -rf "$BASE/Data/novel_embeddings/$SLUG" \
             "$BASE/Data/novel_embeddings_attn_zeroed/$SLUG"
    fi

    # Written last, and only on success, so it means "every step finished".
    # Embeddings are deleted above, so without this a restart would re-extract
    # and re-probe cells that were already done.
    touch "$DONE_MARK"
    log "=== $SLUG complete ==="
  } 2>&1 | tee -a "$LOG" || CELL_OK=0

  if [[ "$CELL_OK" != "1" || ! -f "$DONE_MARK" ]]; then
    FAILED+=("$SLUG")
    log "!!! $SLUG FAILED; continuing to next cell (see $LOG)"
  fi

done < "$JOBS"

if (( ${#FAILED[@]} )); then
  log "FINISHED WITH ${#FAILED[@]} FAILED CELL(S):"
  printf '  %s\n' "${FAILED[@]}"
  log "Re-run the same command to retry only the failed cells."
else
  log "ALL DONE ($N_JOBS cells). Results in $OUT_ROOT"
fi
cat <<EOF

Per cell, $OUT_ROOT/<slug>/ contains:
  linear_probe.csv       linear-probe R2, same folds as the MLP
  pls_sweep.csv          R2 vs number of PLS components (K = 1..$PLS_KMAX)
  linear_directions.npz  fitted directions, keyed condition|layer|mode
  steering.csv           mean preference by intervention layer and alpha
                         (multi-layer cells only)
EOF
