#!/usr/bin/env bash
#
# supplementary_analyses.sh
# -------------------------
# Supplementary probe analyses, for the Ubuntu server.
#
# Additions to the published MLP results, not replacements: nothing here writes
# to by_layer_mlp.csv, cv_preds/, or any other main-pipeline output. Everything
# lands in Data/supplementary/<slug>/.
#
#   1. re-extract embeddings   (the main pipeline deletes them)
#   2. linear probe            same folds as the MLP, so directly comparable
#   3. PLS component sweep     how many dimensions carry the ordering signal
#   4. steering                causal test: is the direction USED, not just decodable
#   5. delete embeddings       (optional; they are very large)
#
# COVERAGE
#   The job list is generated by supplementary_jobs.py, which reads it off
#   Results/*/by_layer_mlp.csv — i.e. exactly the cells the paper reports, at
#   exactly the layer depths they were run at. Nothing is re-derived, so BabyLM
#   and Pythia get their full by-layer and by-checkpoint coverage while
#   GPT-2 / OLMo / Llama get final-layer only, matching the pipeline.
#
#   Preview the job list without running anything:
#       python Scripts/supplementary_jobs.py | column -t
#
# Usage:
#   bash Scripts/supplementary_analyses.sh
#   ONLY="babylm pythia"        bash Scripts/supplementary_analyses.sh
#   FINAL_ONLY=1                bash Scripts/supplementary_analyses.sh
#   EXCLUDE="allenai_OLMo-2-1124-1B" bash Scripts/supplementary_analyses.sh
#   KEEP_EMBEDDINGS=1 SKIP_STEERING=1 bash Scripts/supplementary_analyses.sh
#
set -euo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-python}"
GPU="${GPU:-0}"
PLS_KMAX="${PLS_KMAX:-15}"
KEEP_EMBEDDINGS="${KEEP_EMBEDDINGS:-0}"
SKIP_STEERING="${SKIP_STEERING:-0}"
N_STEER_PAIRS="${N_STEER_PAIRS:-500}"
STEER_ALPHAS="${STEER_ALPHAS:--4 -2 -1 0 1 2 4}"
DRY_RUN="${DRY_RUN:-0}"

OUT_ROOT="$BASE/Data/supplementary"
LOG_DIR="$OUT_ROOT/logs"
mkdir -p "$LOG_DIR"

log() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }

# ── build the job list from what the paper actually reports ──────────────────
JOB_ARGS=()
[[ -n "${ONLY:-}" ]]       && JOB_ARGS+=(--only $ONLY)
[[ "${FINAL_ONLY:-0}" == "1" ]] && JOB_ARGS+=(--final-only)
[[ -n "${EXCLUDE:-}" ]]    && JOB_ARGS+=(--exclude $EXCLUDE)

JOBS="$(mktemp)"
trap 'rm -f "$JOBS"' EXIT
"$PYTHON" "$BASE/Scripts/supplementary_jobs.py" "${JOB_ARGS[@]}" > "$JOBS"
N_JOBS=$(wc -l < "$JOBS")
log "job list: $N_JOBS cells"

if [[ "$DRY_RUN" == "1" ]]; then
  printf 'slug\thf_id\trevision\tn_layers\tbatch\tlayers\n'
  cat "$JOBS"
  exit 0
fi

IDX=0
while IFS=$'\t' read -r SLUG HF_ID REVISION NLAYERS BATCH LAYERS; do
  IDX=$((IDX + 1))
  LOG="$LOG_DIR/${SLUG}.log"
  N_L=$(wc -w <<< "$LAYERS")
  log "=== [$IDX/$N_JOBS] $SLUG  rev=$REVISION  layers=$N_L  -> $LOG"

  REV_ARGS=()
  [[ "$REVISION" != "-" ]] && REV_ARGS=(--revision "$REVISION")

  {
    log "--- 1. extracting embeddings: layers [$LAYERS] ---"
    for COND in "default:binomial:novel_embeddings" \
                "attn_zeroed:attn_zeroed:novel_embeddings_attn_zeroed"; do
      IFS=':' read -r CNAME CCTX CDIR <<< "$COND"
      TARGET="$BASE/Data/$CDIR/$SLUG"
      if compgen -G "$TARGET/layer_*.npz" > /dev/null 2>&1; then
        log "  $CNAME: embeddings present, skipping extraction"
        continue
      fi
      log "  $CNAME: extracting novel-set embeddings"
      "$PYTHON" "$BASE/Scripts/extract_embeddings.py" \
        --model "$HF_ID" "${REV_ARGS[@]}" \
        --data novel --context "$CCTX" \
        --extract word --pool mean \
        --layer $LAYERS \
        --batch-size "$BATCH" --gpu "$GPU" --out "$TARGET"
    done

    log "--- 2+3. linear probe and PLS component sweep ---"
    "$PYTHON" "$BASE/Scripts/supplementary_probes.py" \
      --model-slug "$SLUG" --num-layers "$NLAYERS" \
      --conditions default attn_zeroed \
      --modes mean_pooled words_only \
      --splits pair_novel word_novel \
      --pls-kmax "$PLS_KMAX" --save-directions \
      --layers $LAYERS \
      --out-dir "$OUT_ROOT/$SLUG" --gpu "$GPU"

    # Steering only where several layers were extracted. Applying the
    # intervention at the final layer alone edits the answer immediately before
    # readout and demonstrates nothing; early-layer efficacy is the whole point.
    if [[ "$SKIP_STEERING" != "1" ]] && [[ "$N_L" -ge 3 ]]; then
      log "--- 4. steering: apply layers=[$LAYERS] alphas=[$STEER_ALPHAS] ---"
      "$PYTHON" "$BASE/Scripts/steering.py" \
        --model "$HF_ID" "${REV_ARGS[@]}" --slug "$SLUG" \
        --fit-layer "$NLAYERS" --fit-per-layer \
        --layers $LAYERS --alphas $STEER_ALPHAS \
        --n-pairs "$N_STEER_PAIRS" --data novel --gpu "$GPU" \
        --out "$OUT_ROOT/$SLUG/steering.csv"
    elif [[ "$SKIP_STEERING" != "1" ]]; then
      log "--- 4. steering SKIPPED: only $N_L layer(s) available for this cell ---"
    fi

    if [[ "$KEEP_EMBEDDINGS" != "1" ]]; then
      log "--- 5. removing embeddings (KEEP_EMBEDDINGS=1 to retain) ---"
      rm -rf "$BASE/Data/novel_embeddings/$SLUG" \
             "$BASE/Data/novel_embeddings_attn_zeroed/$SLUG"
    fi

    log "=== $SLUG complete ==="
  } 2>&1 | tee -a "$LOG"

done < "$JOBS"

log "ALL DONE ($N_JOBS cells). Results in $OUT_ROOT"
cat <<EOF

Per cell, $OUT_ROOT/<slug>/ contains:
  linear_probe.csv       linear-probe R2, same folds as the MLP
  pls_sweep.csv          R2 vs number of PLS components (K = 1..$PLS_KMAX)
  linear_directions.npz  fitted directions, keyed condition|layer|mode
  steering.csv           mean preference by intervention layer and alpha
                         (multi-layer cells only)
EOF
